sudo: false
language: rust
cache: cargo
os:
- linux
osx_image: xcode7.1
rust:
- nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python || true; fi
before_script:
- pip install -v 'travis-cargo<0.2' --user
- if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH;
  fi
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
- echo PATH is $PATH
- export RUST_BACKTRACE=1
script:
- |
  travis-cargo clean &&
  travis-cargo build &&
  travis-cargo test
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
  - secure: sZn3hj3DSEymINts4V3qhJ3bO3Epl2TkK/UDGwM5qPU87fnJsLMo4pH1YoJJv42EGMo7UU5G8EkARto5Kjpqdncg8TXZj4VNq3mdEBW219FhgwA6bjuLl+QYj1F0gFVb7SccbjlgH8B6yrWKXfL7HBZJ3c6ymZQSKly66Kv6lWPN8ePW7QTMqK+WUZtgIhR0kBiQSngdfdmyYaAnqCNYoiATE2jSZ7roDmf7GcTiohH+Yt6a39njgqIP6qofVnAWXg37cokrU0pAix0HK2bgfgoSOFd9yYWqPkf3Rr2edJdEXTwOQKkOmPJevrsTowbzrS+VXwuSkGBAtMGw4+CFLT0X1As9+IrGa3jonBotzEkpglOnCiJHRLdPlOrsXuUGD9TGEPrRBqhxwgiMNi6E/G+NX3O9+evZssx93qVhgFAZ1FRzSKJezaOrpRQNF/r5QCcZlQo6ZoCR/Lgd/mHdsnCVyQlN1Ye4rWchws+73zei2Wmdy3gOj8c7O9R7G5wc9PBletAmFfkavS4TKqnbRn5s5AHpaWbnX1kfVfUpnyPTmopMxhwWtQeWuO+s2Q5pSfcXoQK9uBXP4+qfHcF18M6iDimlmZK8NNDqwix0prc7HEHipsSoxN0yoS6AoZmwC5rJ4e4E8FNF0EIHM9T9w0rTzR+Z7txUBg90jXGjkW8=
before_deploy:
  - export RELEASE_FILE=target/debug.tar.gz
  - tar czf $RELEASE_FILE ./target/debug
  - ls -l $RELEASE_FILE
deploy:
  provider: releases
  api_key:
    secure: dn9ahmJQvXOAdmv50KyWq9FnwKYwA4Wk/DoLqUq6cfaAf/ppbaZ1kZ4DQulXnB2eyFfTjgML6YSVn00aK9HtHk6An2pK2G1uJszTynzxOxdHdbrjEAm4AsfZ2WcHH8cggZz+dufyriO5p4AUUM+VdFG1OE5ZKnIyp9tKK23KYfDFZqe9jqMjS35z7x/Cmva4Lc3d50lUoA9Cm5MPE5Z7ggH1BPl2FtBIAyTFF1a1i5NP3YECo5/hczszgGMLecUsLPBV5bp7Y6EK5bndlF05umKqwzdUpZpruBFFyLs/vGcFME9kQxujnobNMAbFXYX1/cmi43bYPGgocNAJ+/6nzVAa+D6RZJCxZNVjoeCwhKK6CgKh3NjQVDi9XwTL7uE0JlPhChWhpZFfRJZYu2Ps59yQjR3RLgjUMMjSVgZMsl7mxkoyAmplF9CJ23GAyKmWwFHi13UucqTnxcSk1Tz7L+soDN8SxM2GYwjtt4L1My8fPtcvyD4a4mqmHMqmkHG2QKdfAub+7FgmVsOb4Pm2Ioab5uG8uaz2qLTDyWdw1tiM0uNFF1Ta9uO6aNWd0bjnGe6sr8VU7SXNETmdLxUCVdxVzMte/65BL9ALPqf20aK/umInzUHFLheGZbRvS7G23S0S1WkAsrugBV7ZvK2Us60JxHu+z9Sp1Q68ElBQjqs=
  file: "RELEASE_FILE"
  on:
    repo: philipc/gimli
    branch: goblin
    tags: true
